# Default properties values
info.build:
  name: test
  description: the test for jpa by lfwang

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
logging.level:
  com.redis: DEBUG